//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: tehDJ.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_tehDJ_H__
#define __WDR_tehDJ_H__

#ifdef __GNUG__
    #pragma interface "tehDJ_wdr.cpp"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_FILENAME 10000
#define ID_LOAD 10001
#define ID_LOCATION 10002
#define ID_SPINBIT 10003
#define ID_TEXTCTRL 10004
#define ID_START 10005
#define ID_STOP 10006
wxSizer *djMain( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_TEXT 10007
#define ID_PREF_AUDIO_DEVICE 10008
#define ID_PREF_AUDIO_RATE 10009
#define ID_PREF_AUDIO_ASIO 10010
#define ID_PREF_AUDIO_STEREO 10011
#define ID_PREF_AUDIO_BITS 10012
#define ID_PREF_AUDIO_BUFFERS 10013
#define ID_PREF_AUDIO_BUFFERS_CTRL 10014
#define ID_PREF_AUDIO_SAMPLES 10015
#define ID_PREF_AUDIO_LATENCY 10016
wxSizer *djPrefsAudio( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_BAND0 10017
#define ID_BAND1 10018
#define ID_BAND2 10019
#define ID_BAND3 10020
#define ID_BAND4 10021
#define ID_BAND5 10022
#define ID_BAND6 10023
#define ID_BAND7 10024
#define ID_BAND8 10025
wxSizer *EQ( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_SONGTIME 10026
#define ID_SONGNAME 10027
#define ID_VISUAL 10028
#define ID_VOLUME 10029
#define ID_EQ_BUTT 10030
#define ID_BACK 10031
#define ID_PAUSE 10032
#define ID_FORWARD 10033
#define ID_BUFF_LEVEL 10034
wxSizer *djMainSmall( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_GAUGE0 10035
#define ID_GAUGE1 10036
#define ID_GAUGE2 10037
#define ID_GAUGE3 10038
#define ID_GAUGE4 10039
#define ID_GAUGE5 10040
#define ID_GAUGE6 10041
#define ID_GAUGE7 10042
wxSizer *EQView( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_PREF_MP3_ENGINE 10043
#define ID_PREF_MP3_THREAD 10044
#define ID_PREF_MP3_DITHER 10045
wxSizer *djPrefsMP3( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_NOTEBOOK 10046
wxSizer *djPrefs( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
